App\Entity\User:
    attributes:
        normalization_context:
            groups: [user_read]
    collectionOperations:
        register:
            method: POST
            path: /users/register
            controller: App\Api\Action\User\Register
            denormalization_context:
                groups: [user_post]
            openapi_context:
                summary: Register a new user
        login:
            method: POST
            route_name: api_login_check
            openapi_context:
                summary: Logs in a user in the API. Username must be user's email
                requestBody:
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    username:
                                        type: string
                                    password:
                                        type: string
                responses:
                    200:
                        description: OK
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        token:
                                            type: string
        resend_activation_email:
            method: POST
            path: /users/resend_activation_email
            controller: App\Api\Action\User\ResendActivationEmail
            deserialize: false
            openapi_context:
                summary: Resend activation email
                requestBody:
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    email:
                                        type: string
                                        required: true
                responses:
                    200:
                        description: OK
                        content: 
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        message:
                                            type: string
        request_reset_password:
            method: POST
            path: /users/request_reset_password
            controller: App\Api\Action\User\RequestResetPassword
            deserialize: false
            openapi_context:
                summary: Requests an email for password reset
                requestBody:
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    email:
                                        type: string
                                        required: true
                responses:
                    200:
                        description: OK
                        content: 
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        message:
                                            type: string

    itemOperations:
        get:
            method: GET
        activate:
            method: PUT
            path: /users/{id}/activate
            controller: App\Api\Action\User\ActivateAccount
            deserialize: false
            denormalization_context:
                groups: [user_activate]
            openapi_context:
                summary: Activates a new user