App\Entity\User:
    attributes:
        id:
            groups: [user_read]
        name:
            groups: [user_read, user_register]
        email:
            groups: [user_read, user_register]
        password:
            groups: [user_register]
        avatar:
            groups: [user_read]
        token:
            groups: [user_activate]
        active:
            groups: [user_read]
        created_at:
            groups: [user_read]
        updated_at:
            groups: [user_read]